
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: transport_api_development

test:
  <<: *default
  database: transport_api_test

production:
  <<: *default
  database: transport_api_production
  username: transport_api
  password: <%= ENV['TRANSPORT_API_DATABASE_PASSWORD'] %>
